### ISSUE TITLE
a_out_scan example doesn't work -> error: 17 invalid count

### ISSUE THREAD

**Issue by LukasBernhardt00** [mccdaq/mcculw#29]
Hello, 
I'm trying to get the a_out_scan.py example running but I keep getting the Error 17: Invalid count. I tried to change the arguments of the function but I didn't find the problem..
Would be great if someone could point me in the right direction 

Lukas

**Comment by jeffreyg3** [comment]
What MCC device are you using?

**Comment by LukasBernhardt00** [comment]
I'm using a RedLab 3103 Card

**Comment by jeffreyg3** [comment]
for the USB-3103, set the number num_points parameter in the a_out_scan() to the number of channels to the number of channels in the scan.
you cannot use the USB-3103 as a streaming output device.  using this function with this device allows you to write 1 value for each channel (up to 8) so that you can achieve simultaneous update (of 1 sample per channel).

**Comment by LukasBernhardt00** [comment]
Okay thank you for your help, that means I can't really use the card for this application...
